Correct the documentation for the `try` command
This came to light when a user commented on the IM channels that they
were surprised by this warning when the documentation says that "Only
try and try-block are required.":

    compilation error: try must be followed by a catch block or a finally block

P.S., The warning is because they had code that (presumably) looked like
`try { ... } except { ... }` that should now look like `try { ... }
catch { ... }`.